# Generated by Django 2.0.5 on 2018-06-06 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logins',
            name='user_id',
        ),
        migrations.AddField(
            model_name='logins',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='manage_profile.Users'),
        ),
        migrations.AlterField(
            model_name='logins',
            name='ip_address',
            field=models.GenericIPAddressField(default=''),
        ),
        migrations.AlterField(
            model_name='logins',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 14, 13, 39, 784484, tzinfo=utc)),
        ),
    ]
