# Generated by Django 2.0.5 on 2018-06-06 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_profile', '0002_auto_20180606_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='logins',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 14, 14, 43, 908056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logins',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_profile.Users'),
        ),
    ]
