# Generated by Django 2.0.5 on 2018-06-06 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_profile', '0003_auto_20180606_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='secondary_email_id',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logins',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 15, 10, 9, 780793, tzinfo=utc)),
        ),
    ]
